project_id = "bugwubrwvlqayxwcazfd"

[functions.request-login-otp]
verify_jwt = false

[functions.verify-login-otp]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = true

[functions.verify-iit-email]
verify_jwt = true

[functions.seed-data]
verify_jwt = true

[functions.scan-events]
verify_jwt = true

[functions.scan-jobs]
verify_jwt = true
