// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  authStorageKeyFor,
  clearStoredAuthSession,
  isInvalidRefreshTokenError,
  migrateLegacyAuthSession,
  resolveSupabaseProjectId,
} from '@/lib/authSessionRecovery';

function normalizeSupabaseUrl(value: string | undefined): string {
  if (!value) return '';

  const parsed = new URL(value);
  const pathname = parsed.pathname.replace(/\/+$/, '');

  // Cloudflare was previously configured with the PostgREST endpoint. The
  // Supabase client needs the project origin so Auth, Functions and Realtime
  // can construct their own service URLs.
  if (pathname === '/rest/v1') {
    parsed.pathname = '/';
  } else if (pathname && pathname !== '/') {
    throw new Error('VITE_SUPABASE_URL must be a Supabase project URL');
  }

  parsed.search = '';
  parsed.hash = '';
  return parsed.toString().replace(/\/$/, '');
}

const SUPABASE_URL = normalizeSupabaseUrl(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase public configuration is missing');
}
if (SUPABASE_PUBLISHABLE_KEY.startsWith('sb_secret_')) {
  throw new Error('Refusing to expose a Supabase secret key in a browser build');
}

const SUPABASE_PROJECT_ID = resolveSupabaseProjectId(SUPABASE_URL, import.meta.env.VITE_SUPABASE_PROJECT_ID);
export const supabaseAuthStorageKey = authStorageKeyFor(SUPABASE_PROJECT_ID);

if (typeof window !== 'undefined') {
  migrateLegacyAuthSession(localStorage, supabaseAuthStorageKey);
}

export const clearSupabaseAuthSession = () => {
  if (typeof window !== 'undefined') clearStoredAuthSession(localStorage, supabaseAuthStorageKey);
};

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    const response = await fetch(input, { ...init, headers });
    const requestUrl = typeof input === 'string'
      ? input
      : input instanceof URL
        ? input.toString()
        : input.url;
    if (!response.ok && requestUrl.includes('/auth/v1/token') && requestUrl.includes('grant_type=refresh_token')) {
      const payload = await response.clone().json().catch(() => null);
      if (isInvalidRefreshTokenError(payload)) clearSupabaseAuthSession();
    }
    return response;
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: supabaseAuthStorageKey,
  }
});

export const supabaseUrl = SUPABASE_URL;
